project_id = "afpxhlhumuoqxrymhyfs"

[functions.analyze-soil]
verify_jwt = false

[functions.verify-subscription]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.soil-chat]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
